<option value="af">Afghanistan</option>
<option value="ax">Alandeilanden</option>
<option value="al">Albani&#235;</option>
<option value="dz">Algerije</option>
<option value="as">Amerikaans Samoa</option>
<option value="vi">Amerikaanse Maagdeneilanden</option>
<option value="um">Amerikaanse kleinere afgelegen eilanden</option>
<option value="ad">Andorra</option>
<option value="ao">Angola</option>
<option value="ai">Anguilla</option>
<option value="aq">Antarctica</option>
<option value="ag">Antigua en Barbuda</option>
<option value="ar">Argentini&#235;</option>
<option value="am">Armeni&#235;</option>
<option value="aw">Aruba</option>
<option value="au">Australi&#235;</option>
<option value="az">Azerbeidzjan</option>
<option value="bs">Bahama&#39;s</option>
<option value="bh">Bahrein</option>
<option value="bd">Bangladesh</option>
<option value="bb">Barbados</option>
<option value="be">Belgi&#235;</option>
<option value="bz">Belize</option>
<option value="bj">Benin</option>
<option value="bm">Bermuda</option>
<option value="bt">Bhutan</option>
<option value="bo">Bolivia</option>
<option value="bq">Bonaire, Sint Eustatius &amp; Saba</option>
<option value="ba">Bosni&#235; en Herzegovina</option>
<option value="bw">Botswana</option>
<option value="bv">Bouveteiland</option>
<option value="br">Brazili&#235;</option>
<option value="io">Britse Gebieden in de Indische Oceaan</option>
<option value="vg">Britse Maagdeneilanden</option>
<option value="bn">Brunei</option>
<option value="bg">Bulgarije</option>
<option value="bf">Burkina Faso</option>
<option value="bi">Burundi</option>
<option value="kh">Cambodja</option>
<option value="ca">Canada</option>
<option value="ky">Caymaneilanden</option>
<option value="cf">Centraal-Afrikaanse Republiek</option>
<option value="cl">Chili</option>
<option value="cn">China</option>
<option value="cx">Christmaseiland</option>
<option value="cc">Cocoseilanden</option>
<option value="co">Colombia</option>
<option value="km">Comoren</option>
<option value="cg">Congo</option>
<option value="cd">Congo-Kinshasa</option>
<option value="ck">Cookeilanden</option>
<option value="cr">Costa Rica</option>
<option value="cu">Cuba</option>
<option value="cw">Cura&#231;ao</option>
<option value="cy">Cyprus</option>
<option value="dk">Denemarken</option>
<option value="dj">Djibouti</option>
<option value="dm">Dominica</option>
<option value="do">Dominicaanse Republiek</option>
<option value="de">Duitsland</option>
<option value="ec">Ecuador</option>
<option value="eg">Egypte</option>
<option value="sv">El Salvador</option>
<option value="gq">Equatoriaal-Guinea</option>
<option value="er">Eritrea</option>
<option value="ee">Estland</option>
<option value="et">Ethiopi&#235;</option>
<option value="fo">Faer&#246;er</option>
<option value="fk">Falklandeilanden</option>
<option value="fj">Fiji</option>
<option value="ph">Filipijnen</option>
<option value="fi">Finland</option>
<option value="fr">Frankrijk</option>
<option value="gf">Frans-Guyana</option>
<option value="pf">Frans-Polynesi&#235;</option>
<option value="tf">Franse Gebieden in de zuidelijke Indische Oceaan</option>
<option value="ga">Gabon</option>
<option value="gm">Gambia</option>
<option value="ge">Georgi&#235;</option>
<option value="gh">Ghana</option>
<option value="gi">Gibraltar</option>
<option value="gd">Grenada</option>
<option value="gr">Griekenland</option>
<option value="gl">Groenland</option>
<option value="gp">Guadeloupe</option>
<option value="gu">Guam</option>
<option value="gt">Guatemala</option>
<option value="gg">Guernsey</option>
<option value="gn">Guinee</option>
<option value="gw">Guinee-Bissau</option>
<option value="gy">Guyana</option>
<option value="ht">Ha&#239;ti</option>
<option value="hm">Heard- en McDonaldeilanden</option>
<option value="hn">Honduras</option>
<option value="hu">Hongarije</option>
<option value="hk">Hongkong SAR van China</option>
<option value="is">IJsland</option>
<option value="ie">Ierland</option>
<option value="in">India</option>
<option value="id">Indonesi&#235;</option>
<option value="iq">Irak</option>
<option value="ir">Iran</option>
<option value="im">Isle of Man</option>
<option value="il">Isra&#235;l</option>
<option value="it">Itali&#235;</option>
<option value="ci">Ivoorkust</option>
<option value="jm">Jamaica</option>
<option value="jp">Japan</option>
<option value="ye">Jemen</option>
<option value="je">Jersey</option>
<option value="jo">Jordani&#235;</option>
<option value="cv">Kaapverdi&#235;</option>
<option value="cm">Kameroen</option>
<option value="kz">Kazachstan</option>
<option value="ke">Kenia</option>
<option value="kg">Kirgizi&#235;</option>
<option value="ki">Kiribati</option>
<option value="kw">Koeweit</option>
<option value="hr">Kroati&#235;</option>
<option value="la">Laos</option>
<option value="ls">Lesotho</option>
<option value="lv">Letland</option>
<option value="lb">Libanon</option>
<option value="lr">Liberia</option>
<option value="ly">Libi&#235;</option>
<option value="li">Liechtenstein</option>
<option value="lt">Litouwen</option>
<option value="lu">Luxemburg</option>
<option value="mo">Macao SAR van China</option>
<option value="mk">Macedoni&#235;</option>
<option value="mg">Madagaskar</option>
<option value="mw">Malawi</option>
<option value="mv">Maldiven</option>
<option value="my">Maleisi&#235;</option>
<option value="ml">Mali</option>
<option value="mt">Malta</option>
<option value="ma">Marokko</option>
<option value="mh">Marshalleilanden</option>
<option value="mq">Martinique</option>
<option value="mr">Mauritani&#235;</option>
<option value="mu">Mauritius</option>
<option value="yt">Mayotte</option>
<option value="mx">Mexico</option>
<option value="fm">Micronesi&#235;</option>
<option value="md">Moldavi&#235;</option>
<option value="mc">Monaco</option>
<option value="mn">Mongoli&#235;</option>
<option value="me">Montenegro</option>
<option value="ms">Montserrat</option>
<option value="mz">Mozambique</option>
<option value="mm">Myanmar</option>
<option value="na">Namibi&#235;</option>
<option value="nr">Nauru</option>
<option value="nl" selected="selected">Nederland</option>
<option value="np">Nepal</option>
<option value="ni">Nicaragua</option>
<option value="nc">Nieuw-Caledoni&#235;</option>
<option value="nz">Nieuw-Zeeland</option>
<option value="ne">Niger</option>
<option value="ng">Nigeria</option>
<option value="nu">Niue</option>
<option value="kp">Noord-Korea</option>
<option value="mp">Noordelijke Marianeneilanden</option>
<option value="no">Noorwegen</option>
<option value="nf">Norfolkeiland</option>
<option value="ug">Oeganda</option>
<option value="ua">Oekra&#239;ne</option>
<option value="uz">Oezbekistan</option>
<option value="om">Oman</option>
<option value="tl">Oost-Timor</option>
<option value="at">Oostenrijk</option>
<option value="pk">Pakistan</option>
<option value="pw">Palau</option>
<option value="ps">Palestijns Gebied</option>
<option value="pa">Panama</option>
<option value="pg">Papoea-Nieuw-Guinea</option>
<option value="py">Paraguay</option>
<option value="pe">Peru</option>
<option value="pn">Pitcairn</option>
<option value="pl">Polen</option>
<option value="pt">Portugal</option>
<option value="pr">Puerto Rico</option>
<option value="qa">Qatar</option>
<option value="ro">Roemeni&#235;</option>
<option value="ru">Rusland</option>
<option value="rw">Rwanda</option>
<option value="re">R &#233;union</option>
<option value="bl">Saint Barth &#233;lemy</option>
<option value="kn">Saint Kitts en Nevis</option>
<option value="lc">Saint Lucia</option>
<option value="pm">Saint Pierre en Miquelon</option>
<option value="vc">Saint Vincent en de Grenadines</option>
<option value="sb">Salomonseilanden</option>
<option value="ws">Samoa</option>
<option value="sm">San Marino</option>
<option value="st">Sao Tom &#233; en Principe</option>
<option value="sa">Saoedi-Arabi&#235;</option>
<option value="sn">Senegal</option>
<option value="rs">Servi&#235;</option>
<option value="cs">Servi&#235; en Montenegro</option>
<option value="sc">Seychellen</option>
<option value="sl">Sierra Leone</option>
<option value="sg">Singapore</option>
<option value="sx">Sint Maarten</option>
<option value="sh">Sint-Helena</option>
<option value="mf">Sint-Maarten</option>
<option value="si">Sloveni&#235;</option>
<option value="sk">Slowakije</option>
<option value="sd">Soedan</option>
<option value="so">Somali&#235;</option>
<option value="es">Spanje</option>
<option value="lk">Sri Lanka</option>
<option value="sr">Suriname</option>
<option value="sj">Svalbard en Jan Mayen</option>
<option value="sz">Swaziland</option>
<option value="sy">Syri&#235;</option>
<option value="tj">Tadzjikistan</option>
<option value="tw">Taiwan</option>
<option value="tz">Tanzania</option>
<option value="th">Thailand</option>
<option value="tg">Togo</option>
<option value="tk">Tokelau</option>
<option value="to">Tonga</option>
<option value="tt">Trinidad en Tobago</option>
<option value="td">Tsjaad</option>
<option value="cz">Tsjechi&#235;</option>
<option value="tn">Tunesi&#235;</option>
<option value="tr">Turkije</option>
<option value="tm">Turkmenistan</option>
<option value="tc">Turks- en Caicoseilanden</option>
<option value="tv">Tuvalu</option>
<option value="uy">Uruguay</option>
<option value="vu">Vanuatu</option>
<option value="va">Vaticaanstad</option>
<option value="ve">Venezuela</option>
<option value="gb">Verenigd Koninkrijk</option>
<option value="ae">Verenigde Arabische Emiraten</option>
<option value="us">Verenigde Staten</option>
<option value="vn">Vietnam</option>
<option value="wf">Wallis en Futuna</option>
<option value="eh">Westelijke Sahara</option>
<option value="by">Wit-Rusland</option>
<option value="zm">Zambia</option>
<option value="zw">Zimbabwe</option>
<option value="za">Zuid-Afrika</option>
<option value="gs">Zuid-Georgi&#235; en Zuidelijke Sandwicheilanden</option>
<option value="kr">Zuid-Korea</option>
<option value="se">Zweden</option>
<option value="ch">Zwitserland</option>